apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: exam
  name: exam
spec:
  containers:
  - command:
    - sh
    - -c
    - echo $EXAM_CODE > /etx/exampcode.txt; sleep 3600;
    image: busybox
    name: exam
    resources: {}
    #env:
    #- name: EXAM_CODE
      #valueFrom:
        #configMapKeyRef:
          #name: exam-config-map
          #key: EXAM_CODE
    envFrom: # add
    - configMapRef: # add
        name: exam-config-map # add
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}