apiVersion: v1
kind: Pod
metadata:
  labels:
    run: managed
  name: managed
  namespace: resource-management
spec:
  containers:
  - image: nginx
    name: managed
    resources:
      requests: # added
        cpu: "200m" # added
      limits: # added
        cpu: "450m" # added
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}