apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app-version: green
    product: my-web-app
  name: green
  namespace: bgd
spec:
  replicas: 3
  selector:
    matchLabels:
      app-version: green
      product: my-web-app
  strategy: {}
  template:
    metadata:
      labels:
        app-version: green
        product: my-web-app
    spec:
      containers:
      - image: nginx:alpine
        name: nginx
        volumeMounts:
        - name: labels
          mountPath: /usr/share/nginx/html
      volumes:
      - name: labels
        downwardAPI:
          items:
            - path: "index.html"
              fieldRef:
                fieldPath: metadata.labels