apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: time-check
  name: time-check
  namespace: dvl1987
spec:
  volumes: # add
      - name: log-volume # add
        emptyDir: {} # add
  containers:
  - image: busybox
    name: time-check
    resources: {}
    env: # add
    - name: TIME_FREQ # add
      valueFrom: # add
        configMapKeyRef: # add
          name: time-config # add
          key: TIME_FREQ # add
    command: ["/bin/sh", "-c", "while true; do date; sleep $TIME_FREQ;done > /opt/time/time-check.log"] # add
    volumeMounts: # add
      - name: log-volume # add log-volume という名前のボリュームを /opt/time にマウント
        mountPath: /opt/time # add
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}