apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: resource
  name: resource
spec:
  containers:
  - image: nginx
    name: resource
    resources:
      limits: # add
        cpu: 1 # add
        memory: 2Gi # add
      requests: # add
        cpu: 500m # add
        memory: 1Gi # add
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}