apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: multiple
  name: multiple
spec:
  containers:
  - image: httpd
    name: primary # edit
    resources: {}
  - image: busybox # add
    name: secondary # add
    command: ["sh", "-c", "sleep 3600"] # add
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}