apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: context
  name: context
spec:
  containers:
  - command:
    - sh
    - -c
    - sleep 3000
    image: busybox
    name: context
    resources: {}
    securityContext: # add
      runAsUser: 1000 # add
      runAsGroup: 3000 # add
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}