apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pv-pod
  name: pv-pod
spec:
  containers:
  - image: nginx
    name: pv-pod
    resources: {}
    volumeMounts: # add
      - mountPath: /etc/my-volume # add PVCで確保したストレージをマウント。
        name: my-volume # add volumeMounts → volumes → persistentVolumeClaim の流れでPVCを参照
  volumes: # add
  - name: my-volume # add
    persistentVolumeClaim: # add
      claimName: my-claim # add PVCの名前を指定
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}