apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: my-busybox
  name: my-busybox
  namespace: dev2406
spec:
  nodeName: controlplane # add
  volumes: # add
    - name: secret-volume # add
      secret: # add
        secretName: dotfile-secret # add
  containers:
    - image: busybox
      name: secret
      command: # add
        - sleep # add
        - "3600" # add
      resources: {}
      volumeMounts: # add
        - name: secret-volume # add
          readOnly: true # add
          mountPath: /etc/secret-volume # add
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
