apiVersion: v1
kind: Pod
metadata:
  name: frontend
  namespace: ambassador
spec:
  volumes: # added
  - name: config # added
    configMap: # added
      name: haproxy-cfg # added
  containers:
  - image: nginx:alpine
    name: frontend
    command: ["sh", "-c", "while true; do sleep 5; date && curl $SERVICE_NAME:8080 -m 2; done"]
    env:
    - name: SERVICE_NAME
      value: "localhost" # edited
  - image: haproxy:alpine # added
    name: haproxy # added
    volumeMounts: # added
    - name: config # added
      mountPath: /usr/local/etc/haproxy # added