apiVersion: v1
kind: Pod
metadata:
  name: logger
  namespace: adapter
spec:
  volumes:
  - name: tmplog
    emptyDir: {}
  - name: config # added
    configMap: # added
      name: fluentd-config # added
  containers:
  - name: fluentd # added
    image: fluent/fluentd:edge # added
    volumeMounts: # added
    - name: tmplog # added
      mountPath: /tmp/log # added
    - name: config # added
      mountPath: /fluentd/etc # added
  - name: logger
    image: busybox
    volumeMounts:
    - name: tmplog
      mountPath: /tmp/log
    args:
    - /bin/sh
    - -c
    - >
      while true;
      do
        echo {\"dt\": \"$(date -u)\"} >> /tmp/log/input.log;
        sleep 10;
      done