apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: tcp-liveness
  name: tcp-liveness
spec:
  containers:
  - image: goproxy/goproxy
    name: tcp-liveness
    ports:
    - containerPort: 8080
    resources: {}
    livenessProbe: # add
      tcpSocket: # add
        port: 8080 # add
      initialDelaySeconds: 5 # add
      periodSeconds: 3 # add
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}