apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: redis-pod
  name: redis-pod
spec:
  containers:
  - image: redis
    name: redis-pod
    resources: {}
    env: # add
    - name: REDIS_HOST # add
      valueFrom: # add
        secretKeyRef: # add
          name: db-secret # add
          key: DB_HOST # add
    - name: REDIS_PASSWORD # add
      valueFrom: # add
        secretKeyRef: # add
          name: db-secret # add
          key: DB_PASSWORD # add
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}