apiVersion: v1
data:
  DB_HOST: MTI3LjAuMC4x
  DB_PASSWORD: Y2hhbmdlaXQ=
kind: Secret
metadata:
  creationTimestamp: "2025-05-03T15:31:42Z"
  name: db-secret
  namespace: default
  resourceVersion: "6049"
  uid: e2b3c537-f61c-4886-a368-57cc8a0599c0
type: Opaque