apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: admindb
  name: admindb
spec:
  tolerations: # add
  # Taintsは、ノードがPodをスケジュールしないようにする「ブロック」のようなもの
  # Tolerationsは、Podが特定のTaintsを許容する設定で、これによりPodはそのノードにスケジュールされる
  - key: "dedicated" # add # Tolerationにより、dedicated=adminというTaintを持つノードにもPodをスケジューリングできるようにする
    operator: "Equal" # add
    value: "admin" # add
    effect: "NoSchedule" # add
  containers:
  - image: redis:alpine
    name: admindb
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}