apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-claim
spec:
  accessModes:
    - ReadWriteMany # PVと同じモードを指定
  volumeMode: Filesystem
  resources:
    requests:
      storage: 200Mi # 必要なサイズは200MB
  storageClassName: manual # PVのStorageClassと一致している