apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: multiple
  name: multiple
spec:
  containers:
  - image: httpd
    name: primary
    resources: {}
  - image: busybox
    name: secondary
    command: ["sh", "-c", "sleep 3600"]
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}