apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: redis
    spec:
      volumes: # add
      - name: data # add
        emptyDir: {} # add
      - name: redis-config # add
        configMap: # add
          name: redis-config # add
      containers:
      - image: redis:alpine
        name: redis
        resources:
          requests: # add
            cpu: "0.2" # add
        volumeMounts: # add
          - name: data # add
            mountPath: /redis-master-data # add
          - name: redis-config # add
            mountPath: /redis-master # add
        ports: # add
          - containerPort: 6379 # add
status: {}